---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
  labels:
    app: minio
    name: minio-secret
type: Opaque
data:
  MINIO_ROOT_USER: YWRtaW4=
  MINIO_ROOT_PASSWORD: YWRtaW5hZG1pbg==
